export const REQ_POST_SIGN_UP_USER = "REQ_POST_SIGN_UP_USER";
export const RES_POST_SIGN_UP_USER = "RES_POST_SIGN_UP_USER";
export const ERR_POST_SIGN_UP_USER = "ERR_POST_SIGN_UP_USER";

export const REQ_POST_SIGN_OUT_USER = "REQ_POST_SIGN_OUT_USER";
export const RES_POST_SIGN_OUT_USER = "RES_POST_SIGN_OUT_USER";
export const ERR_POST_SIGN_OUT_USER = "ERR_POST_SIGN_OUT_USER";

export const CONNECT_TO_WEBSOCKET = "CONNECT_TO_WEBSOCKET";
export const WEBSOCKET_CONNECTION_OPEN = "WEBSOCKET_CONNECTION_OPEN";
export const WEBSOCKET_CONNECTION_CLOSED = "WEBSOCKET_CONNECTION_CLOSED";
export const WEBSOCKET_HANDLE_MESSAGE = "WEBSOCKET_HANDLE_MESSAGE";
export const WEBSOCKET_HANDLE_ERROR = "WEBSOCKET_HANDLE_ERROR";
